# Generated by Django 2.1.5 on 2022-07-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='number_in_stock',
            field=models.IntegerField(),
        ),
    ]
